Add a "Give Feedback" option in Help menu
jendrikseipp/rednotebook pull request #551
Opened 2021-01-10 16:10 UTC by RJ722

Summary of the changes in this pull request:

As mentioned in TODOs, I've added a "Give Feedback" option in Help menu.

(Copy of #550)

Copied suggestion:

I think that it would be better to redirect the user to `.../discussions/new/?category=ideas`. @jendrikseipp what do you think?

2021-01-10 22:43 UTC, jendrikseipp requested changes
Code looks great, thanks! Can you also add a changelog entry, please?

2021-01-10 22:43 UTC, jendrikseipp commented on rednotebook/gui/menu.py
> +                        "Fill out a short form and help us know how we can improve RedNotebook for you"
Let's shorten this to "How can we improve RedNotebook?"

2021-01-11 10:02 UTC, jendrikseipp commented
I think the URL in the R is fine. It's good to show existing discussions before starting a new one.

2021-01-11 16:10 UTC, RJ722 commented
Thanks for the quick review! Added the changelog entry, and changed the sentence.

2021-01-11 16:35 UTC, jendrikseipp commented on rednotebook/gui/menu.py
> +                    _("How we can improve RedNotebook?"),
we can -> can we

2021-01-11 17:16 UTC, RJ722 commented on rednotebook/gui/menu.py
> +                    _("How we can improve RedNotebook?"),
Oops, dome!

2021-01-11 17:31 UTC, merged

2021-01-11 17:31 UTC, jendrikseipp commented
Thanks, Rahul!