Fixing bug #537, image filenames and web links are not included in wo…
jendrikseipp/rednotebook pull request #696
Opened 2023-05-14 02:28 UTC by laraconda

…rds cloud anymore.

## Summary of the changes in this pull request

* TODO

## Pull request checklist

- [ ] I have added an entry in `CHANGELOG.md` including my name and issue and/or pull request number.
- [ ] If applicable: I have removed the corresponding entry in `TODO.md`.

2023-05-16 09:54 UTC, jendrikseipp requested changes
Looks good to me! I only have cosmetic comments.

2023-05-16 09:54 UTC, jendrikseipp commented on rednotebook/gui/clouds.py
> +        # ignoring files and web links in words cloud
```suggestion
        # Ignore files and web links in word clouds.
```

2023-05-16 22:46 UTC, laraconda commented
I'm thinking about adding small tests for this. I should make a new file in tests/ right? Will tox automatically run it if its there?

2023-05-17 07:43 UTC, jendrikseipp commented
Good idea! If it doesn't fit with some other tests that are already there, yes, please add a new test file. Tox will pick it up automatically.

2023-05-30 23:55 UTC, laraconda commented
I tried to write a test for this functionality but since the class Cloud takes an instance of journal, I figured it would be complicated to instanciate Journal and insert simple text into it. @jendrikseipp do you think there's an easy way to do it?

2023-05-31 09:59 UTC, jendrikseipp requested changes

2023-05-31 09:59 UTC, jendrikseipp commented on rednotebook/gui/clouds.py
> +    def _get_words_for_cloud(self, word_count_dict, ignores, includes, tags_count):
I think it's cleaner to just pass the tags_set instead of tags_count to this function.

2023-05-31 09:59 UTC, jendrikseipp commented on rednotebook/gui/clouds.py
> +            if all(not pattern.match(tag) for pattern in ignores)
I like the `not any()` version better (also below) since it almost reads like English text.

2023-05-31 09:59 UTC, jendrikseipp commented on rednotebook/gui/clouds.py
> +        tags_set = set(map(lambda tag_count: tag_count[0][1:], tags_count))
Let's keep the hash signs,
```
tags = {tag for tag, _freq in tags_count}
```
and use 
```
and f"#{word}" not in tags
```
below.

2023-05-31 10:00 UTC, jendrikseipp commented
I agree that testing this is too complicated. So no need to add a test here.

2023-08-20 06:40 UTC, jendrikseipp commented
I'm assuming the ball is in your court. Give me a shout when you want me to review your changes.

2024-05-05 17:06 UTC, merged

2024-05-05 17:06 UTC, jendrikseipp commented
Thanks @laraconda !